version: '3.1'
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "start"]
    ports:
      - "3000:3000"
    environment:
      - APP_URL=http://localhost:3000
      - HOST=localhost
      - PORT=3000

      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=test_db
    depends_on:
      - db

  db:
    container_name: mysql-db
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password && --init-file /docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test_db
    ports:
      - 3306:3306
    volumes:
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
